# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 13:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
